baseURL: "https://jortegab.github.io" 
title: Jose A. Ortega
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 1
        - name: Replication Files
          url: replication/
          weight: 2
        - name: Packages
          url: packages/
          weight: 3
        - name: Blog
          url: blog/
          weight: 4

params:
    description: "I am a MSc. Student in Econometrics at Universidad Torcuato di Tella."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "April 2024"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jose A. Ortega
          subtitle: "I am a MSc. Student in Econometrics at Universidad Torcuato di Tella."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Jose A. Ortega
          buttons:
            - name: Research
              url: research/
            - name: Replication Files
              url: replication/
            - name: Packages
              url: packages/
            - name: Blog
              url: blog/
            #- name: Tags
            #  url: tags/
            #- name: Archive
            #  url: archive/
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:jaortegab.00@gmail.com
        #- name: Location
        #  url: location/
        #- name: Office Hours
        #  url: officehours/
        #- name: Google Scholar
        #  url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        #- name: YouTube
        #  url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/jortegab
        #- name: Substack
        #  url: https://pmichaillat.substack.com
        #- name: Twitter
        #  url: https://twitter.com/pmichaillat

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jose A. Ortega"
      icon: icon.png
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
